version: '2'
services:
  wordpress:
    image: username/webprojectname:1.0
    ports:
      - 80
      - 443
    environment:
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX}_
      WORDPRESS_DB_HOST: ${DB_USER}_db:3306
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SERVER_HOSTNAME: ${SERVER_HOSTNAME}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: srmmhv@gmail.com

      RELAY_NETWORKS_RANGE: ${RELAY_NETWORKS_RANGE}
      RELAY_DOMAINS: ${RELAY_DOMAINS}
      SMARTHOST_ALIASES: ${SMARTHOST_ALIASES}
      SMARTHOST_ADDRESS: ${SMARTHOST_ADDRESS}
      SMARTHOST_PORT: ${SMARTHOST_PORT}
      SMARTHOST_USER: ${SMARTHOST_USER}
      SMARTHOST_PASSWORD: ${SMARTHOST_PASSWORD}
    links:
      - mysql:${DB_USER}_db

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /data/db:/var/lib/mysql

networks:
  default:
    external:
      name: nginx-proxy
