version: '2'
services:
  wordpress:
    image: wordpress:4.8-php7.1
    ports:
      - 80
    volumes:
      - ./html/wp-content:/var/www/html/wp-content
      - ./shell_scripts:/shell_scripts
    environment:
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX}_
      WORDPRESS_DB_HOST: ${DB_USER}_db:3306
      VIRTUAL_PROTO: ${VIRTUAL_PROTO}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    command:
      - cd /tmp && curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && mv wp-cli.phar /bin/wp && chmod 755 /bin/wp
    links:
      - mysql:${DB_USER}_db

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: foobar
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/dump:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/mysql

networks:
  default:
    external:
      name: nginx-proxy
